# Generated by Django 5.0.1 on 2024-01-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameresponse_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvcWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cvc_words')),
                ('group', models.IntegerField()),
                ('difficulty', models.IntegerField()),
            ],
        ),
    ]
