# Generated by Django 5.0.1 on 2024-01-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_cvcword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvcword',
            name='image',
            field=models.ImageField(upload_to='media/cvc_words'),
        ),
    ]
